###
POST https://1f0bbde6-1c5c-4e9a-82c3-ec21ba583692-00-hgbt6xeiwp4q.janeway.replit.dev/api/umbler-sync/trigger    

###
GET http://localhost:5000/api/message-jobs-logs

###
POST http://localhost:5000/api/bling-accounts/e7214073-b339-4f78-9811-3c79b21c8816/import-orders
Content-Type: application/json
x-user-id:224b8f88-e0e6-4c46-b43d-8fbf2dc27f5d
x-user-role: admin

{
  "startDate": "2026-01-01",
  "endDate": "2026-12-31",
  "forceUpdate": true,
  "idSituacao": 9
}

###
GET https://api.bling.com.br/Api/v3/contatos
Authorization: Bearer 38ca64d37594171a6d3d09dcca92a5733a376428